# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20170109_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4)),
                ('value', models.CharField(max_length=4)),
            ],
        ),
    ]
