# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20170109_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
